.TH GWHERE 1
.SH NAME
gwhere \- Catalog manager
.SH SYNOPSIS
.PP
.B gwhere
[
.BR catalog
]
.SH DESCRIPTION
GWhere allows you to manage a database of your CDs and other removable media
(hard disks, floppy drive, Zip drive, CD- ROM, etc...).
With GWhere it's easy to browse your CDs or to make a quick search without
needing to insert all of your CDs in the drive and search them one by one.
.SH OPTIONS
You can specify a catalog file for the program to load on startup by passing
the catalog filename as an argument
.TP
.BR catalog
The filename of a catalog to load at program startup.
.SH AUTHOR
S\['e]bastien LECACHEUR <zero@gwhere.org>

This manual page written by Luis Parravicini <luis@ktulu.com.ar>
